const WEATHER_TABLE = {
  "0": "快晴",
  "1": "晴れ",
  "2": "部分的に曇り",
  "3": "曇り",
  "45": "霧",
  "48": "凍霧",
  "51": "小雨",
  "53": "霧雨",
  "55": "強い霧雨",
  "56": "軽い着氷性の霧雨",
  "57": "着氷性の霧雨",
  "61": "小雨",
  "63": "雨",
  "65": "大雨",
  "66": "軽い着氷性の雨",
  "67": "着氷性の雨",
  "71": "小雪",
  "73": "雪",
  "75": "大雪",
  "77": "雪粒",
  "80": "軽いにわか雨",
  "81": "にわか雨",
  "82": "激しいにわか雨",
  "85": "にわか雪",
  "86": "激しいにわか雪",
  "95": "雷雨",
  "96": "ひょう",
  "99": "激しいひょう"
}

const WEATHER_TABLE_EN = {
  "0":"Clear",
  "1":"Mostly Clear",
  "2":"Partly Cloudy",
  "3":"Cloudy",
  "45":"Fog",
  "48":"Freezing Fog",
  "51":"Light Drizzle",
  "53":"Drizzle",
  "55":"Heavy Drizzle",
  "56":"Light Freezing Drizzle",
  "57":"Freezing Drizzle",
  "61":"Light Rain",
  "63":"Rain",
  "65":"Heavy Rain",
  "66":"Light Freezing Rain",
  "67":"Freezing Rain",
  "71":"Light Snow",
  "73":"Snow",
  "75":"Heavy Snow",
  "77":"Snow Grains",
  "80":"Light Rain Shower",
  "81":"Rain Shower",
  "82":"Heavy Rain Shower",
  "85":"Snow Shower",
  "86":"Heavy Snow Shower",
  "95":"Thunderstorm",
  "96":"Hailstorm",
  "99":"Heavy Hailstorm"
}
